apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: jobs-platform
  labels:
    app: job-service
    app.kubernetes.io/name: job-service
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
        app.kubernetes.io/name: job-service
    spec:
      initContainers:
        - name: create-database
          image: alpine:3.20
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - -c
            - |
              apk add --no-cache postgresql-client && \
              psql -h postgres.postgress.svc.cluster.local -U devops -d postgres -tc \
                "SELECT 1 FROM pg_database WHERE datname = 'jobs'" | grep -q 1 || \
              psql -h postgres.postgress.svc.cluster.local -U devops -d postgres -c \
                "CREATE DATABASE jobs"
      containers:
        - name: job-service
          image: ghcr.io/pascariucosmin93/job-service:0.0.6
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UseSerialGC
                -Xms32m
                -Xmx200m
                -XX:MaxMetaspaceSize=96m
                -XX:TieredStopAtLevel=1
            - name: POSTGRES_HOST
              value: "postgres.postgress.svc.cluster.local"
            - name: POSTGRES_DB
              value: "jobs"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
